### ISSUE TITLE
one-or-more (zero-or-more atom) is wrong

### ISSUE THREAD

**Issue by dany-fu** [hicsail/constellation-js#73]
<img width="293" alt="Screen Shot 2019-05-01 at 10 50 24 AM" src="https://user-images.githubusercontent.com/7750862/57032372-0cf92d80-6bff-11e9-9fe9-f34fdb96caac.png">

**Comment by xin-cao** [comment]
I fixed the visual for this in terms of how it is represented in stateGraph. Can't confirm if this is the desired graph but at least there isn't a phantom node pointing to the epsilon node anymore: 
![Screen Shot 2019-07-24 at 4 18 08 PM](https://user-images.githubusercontent.com/26312918/61825581-a9ae1e80-ae2e-11e9-93a1-c5073b3f5148.png)

**Comment by dany-fu** [comment]
I think one-or-more(zero-or-more) just means zero-or-more? So if we wanted to make the condensed visualization, there just shouldn't be a phantom edge. Regardless, I don't want to bandage the bug because if the underlying graph is wrong then the SBOL will be wrong

**Comment by dany-fu** [comment]
@vidyaap @xin-cao can we close this?

**Comment by dany-fu** [comment]
this is fixed by the simplification rules
